# Generated by Django 3.2.14 on 2022-11-13 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teryt', models.CharField(max_length=11, validators=[django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)])),
                ('okres', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(8), django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
