# Generated by Django 3.2.14 on 2022-11-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dane',
            name='dana1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dane',
            name='dana2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dane',
            name='dana3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dane',
            name='dana4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dane',
            name='dana5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dane',
            name='dana6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dane',
            name='dana7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dane',
            name='dana8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dane',
            name='dana9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
