# Generated by Django 3.2.14 on 2022-11-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pres', '0003_alter_dane_dana1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dane',
            name='okres',
            field=models.DateField(),
        ),
    ]
