# Generated by Django 3.2.14 on 2022-11-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pres', '0004_alter_dane_okres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dane',
            name='dana1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
